name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build-unix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make
